name: ci
on:
  push:
    branches: 
      - master
jobs:
  pylint-score:
    runs-on: ubuntu-latest
    steps:
      - name: Check out to repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Score module with pylint
        run: pylint ./nba_mvp_predictor/ --disable missing-module-docstring,import-error,fixme --fail-under=8.0
  pipfile-lock-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out to repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Make sure the packages are properly locked in Pipfile.lock
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --deploy
